run:
  go: "1.24"
linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - copyloopvar
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forbidigo
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - goconst
  - gocritic
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - iface
  - importas
  - ineffassign
  - intrange
  - loggercheck
  - makezero
  - mirror
  - misspell
  - mnd
  - nakedret
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - reassign
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - tagliatelle
  - testifylint
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - usetesting
  - whitespace
  # Run with --fast=false for more extensive checks
  fast: true

linters-settings:
  gosec:
    severity: medium
    confidence: medium
    concurrency: 8
  importas:
    no-unaliased: true
    alias:
    # Kubernetes
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
      alias: apiextensionsv1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: apierrors
    - pkg: k8s.io/apimachinery/pkg/util/errors
      alias: kerrors
    - pkg: k8s.io/component-base/logs/api/v1
      alias: logsv1
    # Controller Runtime
    - pkg: sigs.k8s.io/controller-runtime
      alias: ctrl
    # KCP
    - pkg: sigs.k8s.io/cluster-api/api/controlplane/kubeadm/v1beta2
      alias: controlplanev1
    # CAPI
    - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
      alias: clusterv1
    - pkg: sigs.k8s.io/cluster-api/api/core/v1beta1
      alias: clusterv1beta1
    - pkg: "sigs.k8s.io/cluster-api/util/deprecated/v1beta1/conditions"
      alias: v1beta1conditions
    - pkg: sigs.k8s.io/cluster-api/util/deprecated/v1beta1/conditions/v1beta2
      alias: deprecatedv1beta2conditions
    - pkg: sigs.k8s.io/cluster-api/util/conditions/deprecated/v1beta1
      alias: deprecatedv1beta1conditions
    - pkg: sigs.k8s.io/cluster-api/util/deprecated/v1beta1/patch
      alias: v1beta1patch
    # CAPM3
    - pkg: github.com/metal3-io/cluster-api-provider-metal3/api/v1beta1
      alias: infrav1
    # BMO
    - pkg: github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1
      alias: bmov1alpha1
  nolintlint:
    allow-unused: false
    require-specific: true
  gocritic:
    enabled-tags:
    - experimental
    disabled-checks:
    - appendAssign
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - evalOrder
    - ifElseChain
    - octalLiteral
    - regexpSimplify
    - sloppyReassign
    - truncateCmp
    - typeDefFirst
    - unnamedResult
    - unnecessaryDefer
    - whyNoLint
    - wrapperFunc
  tagliatelle:
    case:
      rules:
        json: goCamel
  govet:
    enable:
    - shadow

issues:
  exclude-dirs:
  - mock*
  exclude-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  exclude-rules:
  - path: test/e2e
    linters:
    - gosec
  - path: e2e
    linters:
    - mnd
  - path: _test\.go
    linters:
    - unused
    - unparam
    - goconst
    - dupl
    - mnd
  # Specific exclude rules for deprecated fields that are still part of the codebase.
  # These should be removed as the referenced deprecated item is removed from the project.
  - linters:
    - staticcheck
    text: "SA1019:"
  # Disable linters for conversion
  - linters:
    - staticcheck
    text: "SA1019:"
    path: .*(api|types)\/.*\/conversion.*\.go$
  # Dot imports for gomega or ginkgo are allowed
  # within test files.
  - path: _test\.go
    text: should not use dot imports
  - path: (test|e2e)/.*.go
    text: should not use dot imports
  - linters:
    - staticcheck
    text: 'SA1019: "sigs.k8s.io/cluster-api/api/core/v1beta1" is deprecated: This package is deprecated and is going to be removed when support for v1beta1 will be dropped.'
  - linters:
    - staticcheck
    text: 'SA1019: "sigs.k8s.io/cluster-api/api/ipam/v1beta1" is deprecated: This package is deprecated and is going to be removed when support for v1beta1 will be dropped.'
  - linters:
    - staticcheck
    text: 'SA1019: "sigs.k8s.io/cluster-api/util/deprecated/v1beta1/.*" is deprecated'
  - linters:
    - revive
    text: "exported: exported method .*\\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported"
  # Exclude some packages or code to require comments, for example test code, or fake clients.
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    source: (func|type).*Fake.*
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: fake_\.go
  - linters:
    - revive
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - revive
    text: "var-naming: don't use underscores in Go names;"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - revive
    text: "receiver-naming: receiver name"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - stylecheck
    text: "ST1003: should not use underscores in Go names;"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - stylecheck
    text: "ST1016: methods on the same type should have the same receiver name"
    path: .*(api|types)\/.*\/conversion.*\.go$
  - linters:
    - tagliatelle
    text: "DHCP|SLAAC"
  include:
  - EXC0002 # include "missing comments" issues from golangci-lint
  max-issues-per-linter: 0
  max-same-issues: 0
