---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal3-fkas-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal3-fkas-role
rules:
- apiGroups: ["metal3.io", "cluster.x-k8s.io", "infrastructure.cluster.x-k8s.io"]
  resources: ["baremetalhosts", "machines", "clusters", "metal3machines", "metal3clusters"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal3-fkas-rolebinding
subjects:
- kind: ServiceAccount
  name: metal3-fkas-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: metal3-fkas-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: metal3-fkas-system
  namespace: default
spec:
  serviceAccountName: metal3-fkas-sa
  containers:
  - name: metal3-fkas-reconciler
    image: quay.io/metal3-io/metal3-fkas:latest
    imagePullPolicy: IfNotPresent
    command: ["/reconciler"]
  - image: quay.io/metal3-io/metal3-fkas:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    name: metal3-fkas
