name: golangci-lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        working-directory:
        - ""
        - test
        - api
        - hack/fake-apiserver

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: golangci-lint-${{matrix.working-directory}}
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: v2.1.0
        working-directory: ${{matrix.working-directory}}
        args: --timeout=15m
