name: Check Markdown links

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Broken Links
    # This workflow is only of value to the metal3-io/cluster-api-provider-metal3 repository and
    # would always fail in forks
    if: github.repository == 'metal3-io/cluster-api-provider-metal3'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: .markdownlinkcheck.json